kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fakos-metrics-exporter
  namespace: kube-system
  labels:
    prometheus: fakos-metrics-exporter
spec:
  replicas: 1 
  selector:
    matchLabels:
      prometheus: fakos-metrics-exporter
  template:
    metadata:
      labels:
        prometheus: fakos-metrics-exporter
        name: fakos-metrics-exporter
    spec:
      serviceAccountName: fakos-metrics-exporter
      terminationGracePeriodSeconds: 60
      containers:
      - image: christiantragesser/fakos
        name: fakos
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu:  20m
          limits:
            memory: 128Mi
            cpu: 50m