kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.fullname | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.prometheus.labelKey }}: {{ .Values.fullname | quote }}
spec:
  selector:
    {{ .Values.prometheus.labelKey }}: {{ .Values.fullname | quote }}
    name: {{ .Values.fullname | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: {{ .Values.service.name | quote }}
