kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{ .Values.prometheusLabelKey }}: {{ .Values.fullname | quote }}
spec:
  selector:
    {{ .Values.prometheusLabelKey }}: {{ .Values.fullname | quote }}
    name: {{ .Values.fullname | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: {{ .Values.service.name | quote }}
